In [ ]:
import numpy as np

In [ ]:
lista=list(range(1,11))
arreglo=np.array(lista)
type(arreglo)

In [ ]:
arreglo_de_unos=np.ones(20)
print(arreglo_de_unos)
arreglos_ones=arreglo_de_unos.astype(int)
print(arreglos_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


##Usando la Funcion Random

In [ ]:
arreglo_aleatorio= np.random.rand(12)
arreglo_aleatorio

array([0.49007584, 0.95978921, 0.50936609, 0.92145317, 0.75375407,
       0.46044972, 0.49650616, 0.89667453, 0.21333704, 0.50492004,
       0.3732855 , 0.91291852])

##Generar Numeros Aleatorios Del 1 al 5

In [ ]:
arreglo_aleatorio2= np.random.randint(1,100,12)
arreglo_aleatorio2

array([4, 1, 1, 3, 2, 3, 4, 1, 4, 2, 1, 2])

##Matriz

In [ ]:
Matriz=np.random.rand(3,3)
Matriz

array([[0.46291504, 0.52324827, 0.54371173],
       [0.15604927, 0.73860205, 0.29305309],
       [0.77718342, 0.04340826, 0.08459489]])

#Una Matriz consiste de listas en otras listas o una anidacion de arreglos

In [ ]:
Matriz2 = np.random.randint(1,101,(5,12))
Matriz2

array([[67, 92, 43, 14, 86, 60, 63, 69, 68, 15, 58, 71],
       [95, 37, 81, 38,  6,  6, 30, 82, 75, 91, 90, 21],
       [50, 65, 94, 65, 44, 93, 30, 76, 70, 29, 64, 26],
       [28, 34, 85, 70, 14,  8, 46, 68, 74, 99, 96, 86],
       [64, 40, 96, 64,  4, 51, 44, 50,  1, 68, 43, 64]])

##Crear arreglo nueve elementos enteros con random

In [ ]:
Nueve_Elementos=np.random.randint(1,100,9)
Nueve_Elementos

array([61, 37, 67, 50, 18, 45, 63, 88, 43])

##Agregar Imagen

In [ ]:
<image src ="download/img/ACB.png">

SyntaxError: ignored

##Obtener Dimension del arreglo

In [ ]:
np.shape(arreglo)

(10,)

##Crear un arreglo de 12 elementos a uno de 4x3

In [ ]:
matriz= arreglo_aleatorio2.reshape(4,3)
matriz

array([[4, 1, 1],
       [3, 2, 3],
       [4, 1, 4],
       [2, 1, 2]])